export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const UPDATE_SINGLE_PRODUCT = 'UPDATE_PRODUCTS';
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_SINGLE_CATEGORY = "UPDATE_SINGLE_CATEGORY";